//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public int Id_Sklad { get; set; }
        public Nullable<int> Id_Produktii { get; set; }
        public Nullable<int> Kolichestvo { get; set; }
        public Nullable<System.DateTime> Data_postupleniya { get; set; }
    
        public virtual Produkti Produkti { get; set; }
    }
}
