//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazy
    {
        public int Id_Zakazi { get; set; }
        public Nullable<System.DateTime> Data_zakaza { get; set; }
        public Nullable<int> Id_Produkti { get; set; }
        public Nullable<int> Kolichestvo { get; set; }
        public Nullable<int> Stoimost { get; set; }
        public Nullable<int> Id_Postavshik { get; set; }
    
        public virtual Postavchiki Postavchiki { get; set; }
        public virtual Produkti Produkti { get; set; }
    }
}
